In [1]:
import pandas

In [2]:
import pandas as pd

In [4]:
pwd

'/Users/srikumar/AI/Pandas'

In [5]:
ls

Demo_Readme.txt  nyc_weather.csv  Pandas01.ipynb

In [8]:
df = pd.read_csv("nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [9]:
df.tail(2)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [11]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [12]:
df['CloudCover']

0     5
1     3
2     1
3     3
4     0
5     0
6     3
7     8
8     8
9     7
10    1
11    4
12    0
13    7
14    2
15    7
16    6
17    2
18    1
19    2
20    1
21    3
22    8
23    3
24    2
25    2
26    3
27    1
28    4
29    0
30    0
Name: CloudCover, dtype: int64

In [13]:
df[2:5]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [14]:
df[:][2:5]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [15]:
df[2:5]['Temperature']

2    40
3    25
4    20
Name: Temperature, dtype: int64

In [17]:
df[20:30]['Events']

20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
Name: Events, dtype: object

In [18]:
df.head(3)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277

In [21]:
df[['EST', 'Humidity', 'WindSpeedMPH']][:4]

        EST  Humidity  WindSpeedMPH
0  1/1/2016        52           8.0
1  1/2/2016        46           7.0
2  1/3/2016        47           8.0
3  1/4/2016        44           9.0

In [22]:
df['Temperature'].mean()

np.float64(34.67741935483871)

In [23]:
df['Temperature'].max()

50

In [24]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [26]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [32]:
df.Temperature >40

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10    False
11    False
12    False
13    False
14     True
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27    False
28    False
29    False
30     True
Name: Temperature, dtype: bool

In [33]:
df[df.Temperature > 40]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [36]:
df[df.Temperature > 40].Temperature.max()

50

In [47]:
df[df.Temperature == df.Temperature.max()]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [48]:
(df.Temperature == df.Temperature.max())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: Temperature, dtype: bool

In [4]:
import pandas as pd
df = pd.read_csv("nyc_weather.csv")
df[df.Temperature == df.Temperature.max()]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [5]:
df[df.Temperature==df['Temperature'].max()]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [6]:
df[df.Temperature==df.Temperature.max()].Humidity

9    71
Name: Humidity, dtype: int64

In [11]:
df['EST'][df.Temperature == df.Temperature.max()]
# Execution started from right to left
# right side condition [] part - gives a list of true false values 
# then if you add ['EST'] it gives you the value instead of row

9    1/10/2016
Name: EST, dtype: object

In [16]:
df[['Temperature','EST']][df.Temperature==df.Temperature.max()]

   Temperature        EST
9           50  1/10/2016

In [26]:
df['Humidity'].mean()

np.float64(51.67741935483871)

In [27]:
df['Humidity']

0     52
1     46
2     47
3     44
4     41
5     35
6     33
7     64
8     77
9     71
10    37
11    53
12    42
13    47
14    62
15    70
16    66
17    53
18    42
19    49
20    45
21    41
22    78
23    53
24    54
25    56
26    45
27    51
28    50
29    46
30    52
Name: Humidity, dtype: int64

In [29]:
df[['Humidity','CloudCover']][2:5]

   Humidity  CloudCover
2        47           1
3        44           3
4        41           0

In [30]:
df[2:5]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [31]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [32]:
df.head(2)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275

In [33]:
df.tail(3)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [37]:
a = df['Temperature'].max()
print(a)

50

In [39]:
df[df['Temperature'] == a]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [56]:
df[['DewPoint','Events'][:4]]

    DewPoint    Events
0         23       NaN
1         18       NaN
2         21       NaN
3          9       NaN
4         -3       NaN
5          4       NaN
6         11       NaN
7         29       NaN
8         38      Rain
9         46      Rain
10         8       NaN
11        15       NaN
12         4       NaN
13        12       NaN
14        31       NaN
15        37      Rain
16        23  Fog-Snow
17         6      Snow
18         3       NaN
19        15       NaN
20        11       NaN
21         6      Snow
22        21  Fog-Snow
23        11      Snow
24        18       NaN
25        29       NaN
26        22      Rain
27        20       NaN
28        21       NaN
29        16       NaN
30        28       NaN

In [57]:
df[['EST','DewPoint']][:4]

        EST  DewPoint
0  1/1/2016        23
1  1/2/2016        18
2  1/3/2016        21
3  1/4/2016         9

In [61]:
df[['WindSpeedMPH']][15:17]

    WindSpeedMPH
15           7.0
16           6.0

In [81]:
df = pd.read_csv("nyc_weather.csv")

In [82]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [77]:
df.loc('Humidity'==47)
#understand what this code means from google if you want to.. unknown to me

In [84]:
df.set_index('Humidity',inplace=True)
df

,index,EST,Temperature,DewPoint,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Humidity,,,,,,,,,,,
52,0,1/1/2016,38,23,30.03,10,8.0,0,5,NaN,281
46,1,1/2/2016,36,18,30.02,10,7.0,0,3,NaN,275
47,2,1/3/2016,40,21,29.86,10,8.0,0,1,NaN,277
44,3,1/4/2016,25,9,30.05,10,9.0,0,3,NaN,345
41,4,1/5/2016,20,-3,30.57,10,5.0,0,0,NaN,333
35,5,1/6/2016,33,4,30.50,10,4.0,0,0,NaN,259
33,6,1/7/2016,39,11,30.28,10,2.0,0,3,NaN,293
64,7,1/8/2016,39,29,30.20,10,4.0,0,8,NaN,79
77,8,1/9/2016,44,38,30.16,9,8.0,T,8,Rain,76
71,9,1/10/2016,50,46,29.59,4,NaN,1.8,7,Rain,109
37,10,1/11/2016,33,8,29.92,10,NaN,0,1,NaN,289
53,11,1/12/2016,35,15,29.85,10,6.0,T,4,NaN,235
42,12,1/13/2016,26,4,29.94,10,10.0,0,0,NaN,284
47,13,1/14/2016,30,12,29.95,10,5.0,T,7,NaN,266
62,14,1/15/2016,43,31,29.82,9,5.0,T,2,NaN,101
70,15,1/16/2016,47,37,29.52,8,7.0,0.24,7,Rain,340
66,16,1/17/2016,36,23,29.78,8,6.0,0.05,6,Fog-Snow,345
53,17,1/18/2016,25,6,29.83,9,12.0,T,2,Snow,293
42,18,1/19/2016,22,3,30.03,10,11.0,0,1,NaN,293
49,19,1/20/2016,32,15,30.13,10,6.0,0,2,NaN,302
45,20,1/21/2016,31,11,30.15,10,6.0,0,1,NaN,312
41,21,1/22/2016,26,6,30.21,9,NaN,0.01,3,Snow,34
78,22,1/23/2016,26,21,29.77,1,16.0,2.31,8,Fog-Snow,42
53,23,1/24/2016,28,11,29.92,8,6.0,T,3,Snow,327
54,24,1/25/2016,34,18,30.25,10,3.0,0,2,NaN,286
56,25,1/26/2016,43,29,30.03,10,7.0,0,2,NaN,244
45,26,1/27/2016,41,22,30.03,10,7.0,T,3,Rain,311
51,27,1/28/2016,37,20,29.90,10,5.0,0,1,NaN,234
50,28,1/29/2016,36,21,29.58,10,8.0,0,4,NaN,298
46,29,1/30/2016,34,16,30.01,10,7.0,0,0,NaN,257
52,30,1/31/2016,46,28,29.90,10,5.0,0,0,NaN,241

In [83]:
df.reset_index(inplace = True)
df

,index,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [88]:
df[0:1]
# but this gives error - df[[0:5]]
# when you are fetching by columns, use double square brackets to avoid confusion between df['col1'] and df[['col1', 'col2']]

,index,EST,Temperature,DewPoint,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Humidity,,,,,,,,,,,
52,0,1/1/2016,38,23,30.03,10,8.0,0,5,NaN,281